version: '3.8'
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: yarn dev
