version: '3.8'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: yarn dev
